package com.inspekpro.util

import android.content.Context
import android.graphics.*
import android.graphics.pdf.PdfDocument
import com.inspekpro.data.local.entity.InspectionFindingEntity
import com.inspekpro.data.local.entity.InspectionSessionEntity
import com.inspekpro.data.local.entity.SessionSummaryEntity
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.*

object PdfGenerator {

    private const val PAGE_WIDTH = 595 // A4 width in points
    private const val PAGE_HEIGHT = 842 // A4 height in points
    private const val MARGIN = 36f
    private const val CONTENT_WIDTH = PAGE_WIDTH - (MARGIN * 2)

    fun generatePdf(
        context: Context,
        session: InspectionSessionEntity,
        summary: SessionSummaryEntity?,
        findings: List<InspectionFindingEntity>,
        userId: Long,
        companyName: String
    ): File {
        val pdfDocument = PdfDocument()
        var pageNumber = 1
        
        // Setup paint objects
        val paintTitle = Paint().apply {
            color = Color.BLACK
            textSize = 18f
            isFakeBoldText = true
            isAntiAlias = true
        }
        val paintSubtitle = Paint().apply {
            color = Color.DKGRAY
            textSize = 10f
            isAntiAlias = true
        }
        val paintBody = Paint().apply {
            color = Color.BLACK
            textSize = 11f
            isAntiAlias = true
        }
        val paintBold = Paint().apply {
            color = Color.BLACK
            textSize = 11f
            isFakeBoldText = true
            isAntiAlias = true
        }
        val paintFooter = Paint().apply {
            color = Color.GRAY
            textSize = 8f
            isAntiAlias = true
        }
        val paintLine = Paint().apply {
            color = Color.LTGRAY
            strokeWidth = 1f
            style = Paint.Style.STROKE
        }

        // Format date and time
        val dateFormat = SimpleDateFormat("dd MMMM yyyy", Locale("in", "ID"))
        val timeFormat = SimpleDateFormat("HH:mm", Locale("in", "ID"))
        val timestamp = SimpleDateFormat("dd MMMM yyyy HH:mm", Locale("in", "ID")).format(Date())

        // Calculate Report Number (e.g. REP-2026-0001)
        val yearStr = SimpleDateFormat("yyyy", Locale.getDefault()).format(Date(session.scheduledDate))
        val reportNo = "REP-$yearStr-${String.format("%04d", session.sessionId)}"

        // Start Page 1
        var pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNumber).create()
        var page = pdfDocument.startPage(pageInfo)
        var canvas = page.canvas
        var currentY = MARGIN

        // Helper function to draw standard footer on page
        fun drawFooter(c: Canvas, pageNum: Int) {
            c.drawLine(MARGIN, PAGE_HEIGHT - 45f, PAGE_WIDTH - MARGIN, PAGE_HEIGHT - 45f, paintLine)
            c.drawText("Generated by InspekPro • Metadata: Author=InspekPro, Subject=Inspection Report, Creator=InspekPro Android", MARGIN, PAGE_HEIGHT - 32f, paintFooter)
            c.drawText("Hal $pageNum | Generated at: $timestamp WIB", PAGE_WIDTH - MARGIN - paintFooter.measureText("Hal $pageNum | Generated at: $timestamp WIB"), PAGE_HEIGHT - 32f, paintFooter)
        }

        // Helper function to wrap text
        fun drawTextWrapped(text: String, x: Float, y: Float, width: Float, paint: Paint): Float {
            val words = text.split(" ")
            var line = ""
            var localY = y
            val fontHeight = paint.descent() - paint.ascent()
            
            for (word in words) {
                val testLine = if (line.isEmpty()) word else "$line $word"
                val testWidth = paint.measureText(testLine)
                if (testWidth > width) {
                    canvas.drawText(line, x, localY, paint)
                    line = word
                    localY += fontHeight + 2
                } else {
                    line = testLine
                }
            }
            if (line.isNotEmpty()) {
                canvas.drawText(line, x, localY, paint)
                localY += fontHeight + 2
            }
            return localY
        }

        var logoHeightUsed = 0f
        
        // Draw Company Logo if exists
        val logoFile = File(context.filesDir, "company_logo_${userId}.jpg")
        if (logoFile.exists()) {
            try {
                val bitmap = BitmapFactory.decodeFile(logoFile.absolutePath)
                if (bitmap != null) {
                    val maxLogoWidth = 80
                    val maxLogoHeight = 40
                    val ratio = bitmap.width.toFloat() / bitmap.height.toFloat()
                    val logoWidth: Int
                    val logoHeight: Int
                    if (ratio > 1) {
                        logoWidth = maxLogoWidth
                        logoHeight = (maxLogoWidth / ratio).toInt()
                    } else {
                        logoHeight = maxLogoHeight
                        logoWidth = (maxLogoHeight * ratio).toInt()
                    }
                    val scaled = Bitmap.createScaledBitmap(bitmap, logoWidth, logoHeight, true)
                    
                    // Draw logo in the top-right corner
                    val logoX = PAGE_WIDTH - MARGIN - logoWidth
                    canvas.drawBitmap(scaled, logoX, currentY, null)
                    logoHeightUsed = logoHeight.toFloat()
                }
            } catch (e: Exception) {
                // Ignore if logo loading fails
            }
        }

        // Document Title on the left side, vertically centered relative to the logo if logo exists
        val titleY = if (logoHeightUsed > 0f) {
            currentY + (logoHeightUsed / 2f) + (paintTitle.textSize / 3f)
        } else {
            currentY + 16f
        }
        canvas.drawText("LAPORAN INSPEKSI TEKNIS", MARGIN, titleY, paintTitle)
        currentY += Math.max(logoHeightUsed, 28f) + 12f

        // Draw Metadata Info Card
        canvas.drawText("NOMOR LAPORAN: $reportNo", MARGIN, currentY, paintBold)
        canvas.drawText("TANGGAL CETAK: $timestamp WIB", PAGE_WIDTH / 2f + 16, currentY, paintSubtitle)
        currentY += 16f
        canvas.drawLine(MARGIN, currentY, PAGE_WIDTH - MARGIN, currentY, paintLine)
        currentY += 20f

        // Table metadata
        val colWidth = CONTENT_WIDTH / 2f
        canvas.drawText("Objek / Mesin:", MARGIN, currentY, paintSubtitle)
        canvas.drawText("Lokasi:", PAGE_WIDTH / 2f, currentY, paintSubtitle)
        currentY += 14f
        canvas.drawText(session.title, MARGIN, currentY, paintBold)
        canvas.drawText(session.locationName, PAGE_WIDTH / 2f, currentY, paintBold)
        currentY += 24f

        canvas.drawText("Inspector:", MARGIN, currentY, paintSubtitle)
        canvas.drawText("Tanggal Jadwal:", PAGE_WIDTH / 2f, currentY, paintSubtitle)
        currentY += 14f
        canvas.drawText(session.inspectorName, MARGIN, currentY, paintBold)
        canvas.drawText(dateFormat.format(Date(session.scheduledDate)), PAGE_WIDTH / 2f, currentY, paintBold)
        currentY += 24f

        canvas.drawText("Perusahaan:", MARGIN, currentY, paintSubtitle)
        canvas.drawText("Hasil Akhir:", PAGE_WIDTH / 2f, currentY, paintSubtitle)
        currentY += 14f
        canvas.drawText(companyName, MARGIN, currentY, paintBold)
        
        val resultStr = if (summary != null) {
            "${summary.passCount} Lolos, ${summary.failCount} Temuan (Skor Kepatuhan: ${summary.complianceScore.toInt()}%)"
        } else {
            "${session.passedItems} Lolos, ${session.failedItems} Gagal"
        }
        canvas.drawText(resultStr, PAGE_WIDTH / 2f, currentY, paintBold)
        currentY += 36f

        // Divider
        canvas.drawLine(MARGIN, currentY, PAGE_WIDTH - MARGIN, currentY, paintLine)
        currentY += 20f

        // General Notes
        canvas.drawText("CATATAN / KESIMPULAN INSPEKSI", MARGIN, currentY, paintBold)
        currentY += 16f
        currentY = drawTextWrapped(session.notes.ifBlank { "Tidak ada catatan kesimpulan tambahan." }, MARGIN, currentY, CONTENT_WIDTH, paintBody)
        currentY += 24f

        // Divider
        canvas.drawLine(MARGIN, currentY, PAGE_WIDTH - MARGIN, currentY, paintLine)
        currentY += 20f

        // Findings section header
        canvas.drawText("DAFTAR TEMUAN LAPORAN (${findings.size})", MARGIN, currentY, paintBold)
        currentY += 16f

        // List findings
        if (findings.isEmpty()) {
            canvas.drawText("Tidak ada temuan kelainan/kerusakan selama inspeksi.", MARGIN, currentY, paintBody)
            currentY += 20f
        } else {
            for (finding in findings) {
                // Check if page overflows
                if (currentY > PAGE_HEIGHT - 120f) {
                    drawFooter(canvas, pageNumber)
                    pdfDocument.finishPage(page)
                    pageNumber++
                    pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNumber).create()
                    page = pdfDocument.startPage(pageInfo)
                    canvas = page.canvas
                    currentY = MARGIN + 16f
                }

                val severityStr = when (finding.severity.name) {
                    "CRITICAL" -> "Kritis"
                    "MAJOR" -> "Mayor"
                    "MINOR" -> "Minor"
                    else -> "Observasi"
                }

                canvas.drawText("• Code: ${finding.findingCode} | Kategori: ${finding.category} [Severity: $severityStr]", MARGIN, currentY, paintBold)
                currentY += 14f
                currentY = drawTextWrapped("Detail: ${finding.description}", MARGIN + 12, currentY, CONTENT_WIDTH - 12, paintBody)
                currentY += 10f
            }
        }

        // Draw general report photos gallery
        // Extract photos from findings
        val findingPhotos = findings.flatMap { finding ->
            parsePhotoPaths(finding.photoPaths)
        }
        
        // Extract photos from general inspection (from description column)
        var generalPhotos: List<String> = emptyList()
        if (!session.description.isNullOrBlank()) {
            try {
                val gson = com.google.gson.Gson()
                try {
                    val payload = gson.fromJson(session.description, com.inspekpro.ui.viewmodel.SessionPayload::class.java)
                    if (payload?.photos != null) {
                        generalPhotos = payload.photos
                    }
                } catch (e: Exception) {
                    // Fallback for old format
                    val type = object : com.google.gson.reflect.TypeToken<List<String>>() {}.type
                    generalPhotos = gson.fromJson(session.description, type) ?: emptyList()
                }
            } catch (e: Exception) {
                e.printStackTrace()
            }
        }

        val photoPaths = (generalPhotos + findingPhotos).distinct()

        if (photoPaths.isNotEmpty()) {
            // Divider
            if (currentY < PAGE_HEIGHT - 120f) {
                canvas.drawLine(MARGIN, currentY, PAGE_WIDTH - MARGIN, currentY, paintLine)
                currentY += 20f
            }

            // Check if gallery title overflows
            if (currentY > PAGE_HEIGHT - 100f) {
                drawFooter(canvas, pageNumber)
                pdfDocument.finishPage(page)
                pageNumber++
                pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNumber).create()
                page = pdfDocument.startPage(pageInfo)
                canvas = page.canvas
                currentY = MARGIN + 16f
            }

            canvas.drawText("LAMPIRAN FOTO DOKUMENTASI", MARGIN, currentY, paintBold)
            currentY += 20f

            val thumbnailWidth = 140f
            val thumbnailHeight = 100f
            val spacing = 16f
            var currentX = MARGIN

            for (path in photoPaths) {
                val imgFile = File(path)
                if (imgFile.exists()) {
                    // Check horizontal overflow
                    if (currentX + thumbnailWidth > PAGE_WIDTH - MARGIN) {
                        currentX = MARGIN
                        currentY += thumbnailHeight + spacing
                    }

                    // Check vertical overflow (new page for photos)
                    if (currentY + thumbnailHeight > PAGE_HEIGHT - 80f) {
                        drawFooter(canvas, pageNumber)
                        pdfDocument.finishPage(page)
                        pageNumber++
                        pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNumber).create()
                        page = pdfDocument.startPage(pageInfo)
                        canvas = page.canvas
                        currentY = MARGIN + 16f
                        currentX = MARGIN
                    }

                    try {
                        val bitmap = BitmapFactory.decodeFile(imgFile.absolutePath)
                        if (bitmap != null) {
                            val scaled = Bitmap.createScaledBitmap(bitmap, thumbnailWidth.toInt(), thumbnailHeight.toInt(), true)
                            canvas.drawBitmap(scaled, currentX, currentY, null)
                            currentX += thumbnailWidth + spacing
                        }
                    } catch (e: Exception) {
                        // Draw empty gray block if bitmap decoding fails
                        val rect = RectF(currentX, currentY, currentX + thumbnailWidth, currentY + thumbnailHeight)
                        val grayPaint = Paint().apply { color = Color.LTGRAY }
                        canvas.drawRect(rect, grayPaint)
                        canvas.drawText("[Gagal Memuat Foto]", currentX + 10, currentY + thumbnailHeight / 2, paintSubtitle)
                        currentX += thumbnailWidth + spacing
                    }
                }
            }
        }

        // Draw last page footer
        drawFooter(canvas, pageNumber)
        pdfDocument.finishPage(page)

        // Save PDF to cache or external files dir
        val outputDir = context.getExternalFilesDir(null) ?: context.cacheDir
        val sanitizedTitle = session.title.replace(" ", "_").replace("/", "_")
        val outputFile = File(outputDir, "${reportNo}_$sanitizedTitle.pdf")

        FileOutputStream(outputFile).use { out ->
            pdfDocument.writeTo(out)
        }
        pdfDocument.close()

        return outputFile
    }

    private fun parsePhotoPaths(jsonStr: String): List<String> {
        if (jsonStr.isBlank()) return emptyList()
        return try {
            val jsonArray = org.json.JSONArray(jsonStr)
            val list = mutableListOf<String>()
            for (i in 0 until jsonArray.length()) {
                list.add(jsonArray.getString(i))
            }
            list
        } catch (e: Exception) {
            if (jsonStr.contains(",")) {
                jsonStr.split(",").map { it.trim() }.filter { it.isNotBlank() }
            } else {
                listOf(jsonStr.trim()).filter { it.isNotBlank() }
            }
        }
    }
}
